services:
  - type: web
    name: lies-Server-9ayj
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 8080

  - type: web
    name: lies-client-9ayj
    env: Production
    buildCommand: cd client && rm -rf node_modules && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https:/lies-server-9ayj.onrender.com